language: node_js
node_js:
- 12
services: mongodb
env:
  - secure: RsuBP3hwFu4aCi6a+wqAO3OcRU/HJrz/it1PfSJoqnfR7nmHg4nIKf8KNdE0cpHpwpaSKAdSUysT05uHxe8RVn+H9BM2xHhKEZ51lYGJk1jtUT0pWNSbOhOrO0h6YOrm+AA5Ff0LHNVQelAmNUu5DK8OGuKQ/sfrAUWKripBYVT6o95BTGf4L2f/EfzJsDUCwaRVWGyqsuxVHAI2xQmnUudklWZGymPEeDCK+nJJhznDz9oURGs2EAff8hSOev+OiUmMlmRk52rqGRm+qwIDoM2+ZZ8tSRyrtl10Lr2Qu9duSTuDa3vks6fRRszZztr0A8f6eTd0U1qidSdCepTwktSiiJWyXqhoIb7cJoGbTVMn/cCC+tiaMjnGu6B0xn+818FYdSIKAl/ftufNuPo3O+dGnDAvkSYMx7g7GR9wH+FcRv/fzhS48EZvtguvzZfa8wACurIU4gc2nKl9OZB9+B4ig7ujgLUR2X/LPgfcDEkD/czVa+X9GIOlreBTF4iUwvyWDzA1F1rwjjeQ5zx+udqRDDuo+NsSptOm0tYFQEV0Vl3mafWMc+sOfm9rISrMozJIuqbsSmhZ8QETq0IuLUWEOmJDYXmjIyqJOP/BmRuVhJAkkZxl8DJZbdQhC6TmiHREcY6AX1pXoddF1keh82G47/zEeNjgsNamtCrm7j4=
before_install:
- cd frontend
- openssl aes-256-cbc -K $encrypted_f311055f652d_key -iv $encrypted_f311055f652d_iv -in frontend.json.enc -out frontend.json -d
- cd ../ && cd backend
- openssl aes-256-cbc -K $encrypted_1a51155dc686_key -iv $encrypted_1a51155dc686_iv -in backend.json.enc -out backend.json -d
before_script:
- npm install mocha chai
script:
- npm test
- cd ../ && cd frontend
- npm install && npm run build && cd ../ && cd backend
before_deploy:
- echo ********** DEPLOYING TO GOOGLE APP ENGINE **********
deploy:
- provider: gae
  keyfile: backend.json
  edge: true
  project: cs3219-assignment-b-backend
- provider: gae
  keyfile: frontend.json
  edge: true
  project: cs3219-assignment-b-frontend
after_deploy:
- cd ../ && cd frontend
